"""add synthetic patient EHR tables + run.patient_id

Revision ID: 0855ddf7084c
Revises: afd411c633db
Create Date: 2026-06-16 08:34:36.131111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) used in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '0855ddf7084c'
down_revision: Union[str, Sequence[str], None] = 'afd411c633db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mrn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('given_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('family_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dob', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sex', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=False)
    op.create_index(op.f('ix_patients_org_id'), 'patients', ['org_id'], unique=False)
    op.create_table('conditions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clinical_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('onset_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_patient_id'), 'conditions', ['patient_id'], unique=False)
    op.create_table('coverages',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relationship', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_end', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverages_patient_id'), 'coverages', ['patient_id'], unique=False)
    op.create_table('treatment_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_records_patient_id'), 'treatment_records', ['patient_id'], unique=False)
    op.add_column('runs', sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_runs_patient_id'), 'runs', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'runs', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_index(op.f('ix_runs_patient_id'), table_name='runs')
    op.drop_column('runs', 'patient_id')
    op.drop_index(op.f('ix_treatment_records_patient_id'), table_name='treatment_records')
    op.drop_table('treatment_records')
    op.drop_index(op.f('ix_coverages_patient_id'), table_name='coverages')
    op.drop_table('coverages')
    op.drop_index(op.f('ix_conditions_patient_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_patients_org_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
