"""add reference catalogs (doc_types, procedures)

Revision ID: 548a36992e65
Revises: 5d607d849e5c
Create Date: 2026-06-16 18:11:29.546897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) used in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '548a36992e65'
down_revision: Union[str, Sequence[str], None] = '5d607d849e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_types',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_types_token'), 'doc_types', ['token'], unique=True)
    op.create_table('procedures',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedures_code'), 'procedures', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procedures_code'), table_name='procedures')
    op.drop_table('procedures')
    op.drop_index(op.f('ix_doc_types_token'), table_name='doc_types')
    op.drop_table('doc_types')
    # ### end Alembic commands ###
