"""add gold_cards table

Revision ID: 5d607d849e5c
Revises: 0855ddf7084c
Create Date: 2026-06-16 10:23:36.308505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) used in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '5d607d849e5c'
down_revision: Union[str, Sequence[str], None] = '0855ddf7084c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_cards',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_npi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('procedure_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('procedure_display', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approvals', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('basis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_cards_org_id'), 'gold_cards', ['org_id'], unique=False)
    op.create_index(op.f('ix_gold_cards_procedure_code'), 'gold_cards', ['procedure_code'], unique=False)
    op.create_index(op.f('ix_gold_cards_provider_npi'), 'gold_cards', ['provider_npi'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gold_cards_provider_npi'), table_name='gold_cards')
    op.drop_index(op.f('ix_gold_cards_procedure_code'), table_name='gold_cards')
    op.drop_index(op.f('ix_gold_cards_org_id'), table_name='gold_cards')
    op.drop_table('gold_cards')
    # ### end Alembic commands ###
