"""add policy_rules table

Revision ID: 6fddce28a00b
Revises: 689db1b29bad
Create Date: 2026-06-16 18:47:16.789421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) used in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '6fddce28a00b'
down_revision: Union[str, Sequence[str], None] = '689db1b29bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_rules',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('procedure_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('required_diagnosis_prefixes', sa.JSON(), nullable=False),
    sa.Column('required_docs', sa.JSON(), nullable=False),
    sa.Column('step_therapy_docs', sa.JSON(), nullable=False),
    sa.Column('red_flag_prefixes', sa.JSON(), nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_procedure_code'), 'policy_rules', ['procedure_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_rules_procedure_code'), table_name='policy_rules')
    op.drop_table('policy_rules')
    # ### end Alembic commands ###
