"""add organizations.kind (provider|payer role)

Revision ID: 75082213c2b4
Revises: 6fddce28a00b
Create Date: 2026-06-17 09:04:21.419895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) used in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = '75082213c2b4'
down_revision: Union[str, Sequence[str], None] = '6fddce28a00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add NOT NULL with a server_default so existing rows backfill to 'provider', then drop the
    # server_default — the value comes from the app default (OrgKind.PROVIDER) going forward.
    # The two demo orgs get their real sides ('payer' for Meridian) from the seed afterwards.
    op.add_column('organizations',
                  sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(),
                            nullable=False, server_default='provider'))
    op.alter_column('organizations', 'kind', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'kind')
    # ### end Alembic commands ###
