"""add run mode + workflow state for interactive PA flow

Revision ID: afd411c633db
Revises: 3ea8838ed24e
Create Date: 2026-06-16 06:16:30.313831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel column types (e.g. AutoString) used in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = 'afd411c633db'
down_revision: Union[str, Sequence[str], None] = '3ea8838ed24e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (autoplay runs); the app always sets these going forward.
    op.add_column('runs', sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(),
                                    nullable=False, server_default='auto'))
    op.add_column('runs', sa.Column('workflow', sa.JSON(), nullable=False,
                                    server_default=sa.text("'{}'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'workflow')
    op.drop_column('runs', 'mode')
    # ### end Alembic commands ###
